name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # 运行构建命令，这个命令应生成 dist 目录

      - name: List build directory contents
        run: ls -la dist  # 确保 dist 目录存在并包含文件

      - name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          path: dist  # 上传 dist 目录作为工件
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
